version: "2.4"

services:
  android:
    image: us.gcr.io/literal-269716/automl-highlight-detection-data-android:latest
    build: ./android
    privileged: true
    ports:
      - 5037:5037
      - 4723:4723
  node:
    image: us.gcr.io/literal-269716/automl-highlight-detection-data-node:latest
    build: ./js
    depends_on:
      - android
    environment:
      ANDROID_EMULATOR_HOSTNAME: android
      ANDROID_EMULATOR_PORT: 5037
      APPIUM_HOSTNAME: "android"
      APPIUM_PORT: 4723
